---
driver:
  name: docker
  privileged: true
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-14.04
  driver_config:
    image: ubuntu:14.04
    platform: ubuntu
    use_sudo: false
    privileged: true
suits:
- name: default
  run_list:
  - recipe[riemann::default]
